### ISSUE TITLE
V2 version

### ISSUE THREAD

**Issue by vcvrackideas** [EnigmaCurry/vcv-pack#1]
Hi! It seems very interesting module to try. Do you plan to migrate it to final V2 SDK? https://community.vcvrack.com/t/rack-development-blog/5864/75?u=vcvrackideas

**Comment by EnigmaCurry** [comment]
Hi! Yes, that's the plan. I started working with 1.1.6, but I am now testing with v2 from git. It seems to work now with only [updating the version number](https://github.com/EnigmaCurry/vcv-pack/blob/master/plugin.json#L4). 

Thanks very much for your interest, and for all your videos. I have learned a ton from you! If you have any suggestions, let me know.

**Comment by EnigmaCurry** [comment]
I've now created two branches for v1 and v2.
