### ISSUE TITLE
Ableton like workflow without stopping a whole transport

### ISSUE THREAD

**Issue by vcvrackideas** [EnigmaCurry/vcv-pack#2]
Hi! I tested this module yesterday. Quite nice idea but each time transport is stopping together with recording ended is not exaclty I personally want to achieve...for example there is the patch playing and I want to take some perfect sync audio into Lilac Looper. Just tap arm and get continously playing recording after 8 bars of recording but transport would be still in playing state. What do you think is this possible to achieve? Maybe with current build and settings, maybe I'm missing something. Cheers!

**Comment by EnigmaCurry** [comment]
Cool, yes I was thinking the same thing. I changed it, so now the playback continues by default. You can also right click and choose "Stop on record length" to have it the way it was before.

So this is how I'm testing it now:
 * Right click and choose Arm quantize of 4.
 * Start play.
 * Later on, arm the recording, and it will flash until the counter is a multiple of 4, and it will then start recording.
 * Anytime during recording, disarm the recording, and it will again flash, and then turn off recording when it reaches a counter multiple of 4.
 * playback continues and the recording is finished.

I tried this with nysti simpliciter and I tied the Mix to the RGAT out of transport, so simpliciter listens to the input when recording, and then switches to the recording for the second loop through.

**Comment by EnigmaCurry** [comment]
I've attempted to clarify all this in the README now.

**Comment by EnigmaCurry** [comment]
I'm still finding lots of bugs, lol. I will get it working soon!

**Comment by EnigmaCurry** [comment]
I made some fixes, and I tested it in recording session yesterday, and I think its working well now. I'll close this issue but if you test it again and find any new issues, please re-open this or open a new one. Thanks!

**Comment by EnigmaCurry** [comment]
FYI : I have made a new patch (VCV selection) with Lilac Looper like you suggested (See notes inside the patch):

https://github.com/EnigmaCurry/EnigmaCurry-vcv-pack/raw/v2/patches/Selections/Transport%20Looper.vcvs

![image](https://user-images.githubusercontent.com/43061/194116559-c8ef6a38-6fc9-4f1f-9913-d51a433cd83c.png)
